name: spiking-nn
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cmake=3.19.6
  - cryptography=3.4.7
  - cudatoolkit=11.1.1
  - freetype=2.10.4
  - future=0.18.2
  - idna=2.10
  - intel-openmp=2020.3
  - jpeg=9b
  - libpng=1.6.37
  - libtiff=4.2.0
  - libuv=1.41.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-include=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.2.0
  - ninja=1.10.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.2.3
  - pillow=8.1.2
  - pip=21.0.1
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - requests=2.25.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.3
  - tk=8.6.10
  - typing_extensions=3.7.4.3
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.11.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.1
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.27.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - ipykernel==5.5.0
    - ipython==7.20.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.11
    - jupyter-console==6.2.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras==2.4.3
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclient==0.5.2
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nengo==3.2.0.dev0
    - nengo-dl==3.4.1.dev0
    - nest==1.3.0
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - openpyxl==3.0.7
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.1
    - pickleshare==0.7.5
    - progressbar2==3.53.1
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.16
    - protobuf==3.15.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.2
    - pydotplus==2.0.2
    - pygments==2.8.0
    - pymatreader==0.0.24
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-graphviz==0.16
    - python-utils==2.5.6
    - pywin32==300
    - pywinpty==0.5.7
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - qtconsole==5.0.2
    - qtpy==1.9.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.1
    - scikit-learn==0.24.1
    - scipy==1.6.1
    - send2trash==1.5.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - torch==1.8.1+cu111
    - torchaudio==0.8.1
    - torchvision==0.9.1+cu111
    - tornado==6.1
    - traitlets==5.0.5
    - urllib3==1.26.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xlrd==2.0.1
    - xmltodict==0.12.0
